[build]
  command = "ng build --configuration production"
  publish = "dist/library-frontend"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[plugins]
  # empty plugin list disables angular plugin
